name: Deploy to GHPages
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Check out current repo
      - uses: actions/checkout@v3
      # Check out sim repo
      - uses: actions/checkout@v3
        with:
          repository: 'W-A-James/mips_sim_v2'
          path: 'sim'
      # Check out Web-app repo
      - uses: actions/checkout@v3
        with:
          repository: 'W-A-James/MIPSView_v2_UI'
          path: 'www'
      - uses: actions/setup-node@v2
        with:
            node-version: 16
      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'v0.10.2'
      - name: Build page
        run: |
          mkdir public
          pwd
          ls -lah

          cd sim
          wasm-pack build

          cd ../www
          npm install && npm run build

      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target-branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
