name: Deploy to GHPages
on:
  push:
    branches: [ master ]
  workflow-dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
          with: 
            node-version: 16
      - name: Build page
        run: |
          mkdir public

          cargo install wasm-pack
          cd sim && wasm-pack build

          cd ..
          cd www
          npm install && npm run build

      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target-branch: gh-pages
          build_dir: public
